export type { ISharedState } from './config/stateSchema'
export type { TAppDispatch } from './config/store'
export type { IReduxStoreWithManager } from './config/stateSchema'
export { createReduxStore } from './config/store'
export { StoreProvider } from './ui/StoreProvider'
