export { articleDetailsRecommendationReducer } from './model/slices/articleDetailsRecommendation'
export type { IArticleRecommendationState } from './model/types'
export { articleDetailsCommentsReducer } from './model/slices/articleDetailsCommentsSlice'
export type { IArticleCommentsState } from './model/types'
export { LazyArticleDetailsPage as ArticleDetailsPage } from './ui/ArticleDetailsPage/ArticleDetailsPage.async'
