export { articlesPageActions } from './model/actions'
export { articlesPageSliceActions } from './model/slices/articlesPageSlice'
export { articlesPageReducer } from './model/slices/articlesPageSlice'
export type { IArticlesPageState } from './model/types'
export { LazyArticlesPage as ArticlesPage } from './ui/ArticlesPage.async'
